---
apiVersion: v2
name: yacht-dispatcher
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: 0.1.3

dependencies:
- name: sthings-helm-toolkit
  version: 2.4.40
  repository: oci://eu.gcr.io/stuttgart-things
