apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yacht-dispatcher-deployment
  namespace: argocd
spec:
  project: app
  destination:
    name: dev11
    namespace: yacht
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: yacht-dispatcher
    targetRevision: 0.1.20
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            configmaps:
              yd-configuration:
                YW_IMAGE: eu.gcr.io/stuttgart-things/yacht-worker:23.0524.1959-0.1.6
                TEKTON_NAMESPACE: tekton-cd
                YACHT_NAMESPACE: yacht
                STATUS_TO_ELASTICSEARCH: "TRUE"
                ELASTICSEARCH_URL: http://10.100.136.150:9200
                ELASTICSEARCH_STATUS_INDEX: yacht-worker-status
            deployment:
              containers:
                yacht-dispatcher:
                  secretsEnvFrom:
                    - name: redis-connection
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
targetRevision: 0.1.17
